// <auto-generated />
using System;
using MainPostsAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainPostsAPI.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MainPostsAPI.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("IsAProject")
                        .HasColumnType("bit")
                        .HasColumnName("is_a_project");

                    b.Property<bool>("PostActive")
                        .HasColumnType("bit")
                        .HasColumnName("post_active");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("post_date");

                    b.Property<string>("PostDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("post_description");

                    b.Property<string>("PostImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_image");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("post_title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MainPostsAPI.Models.PostItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adress");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("PostType")
                        .HasColumnType("int")
                        .HasColumnName("post_type");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subtitle");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostItems");
                });

            modelBuilder.Entity("MainPostsAPI.Models.PostItem", b =>
                {
                    b.HasOne("MainPostsAPI.Models.Post", null)
                        .WithMany("PostItens")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainPostsAPI.Models.Post", b =>
                {
                    b.Navigation("PostItens");
                });
#pragma warning restore 612, 618
        }
    }
}
